### ISSUE TITLE
Parameters with characters outside of azAZ09_

### ISSUE THREAD

**Issue by dodysw** [hugapi/hug#440]
Does hug support parameters that contains characters invalid for a Python variable? E.g: hub.verify_token

**Comment by cag** [comment]
I believe not, because falcon does not support it:

https://github.com/falconry/falcon/blob/master/falcon/routing/compiled.py#L63
```python
        for field in fields:
            is_identifier = re.match('[A-Za-z_][A-Za-z0-9_]*$', field)
            if not is_identifier or field in keyword.kwlist:
```

**Comment by dodysw** [comment]
Thanks, it's really too bad this limitation exists simply due to a choice of underlying library (or possibly, an inappropriate abstraction). Guess I just not realized early what compromises hug has made when it creates those beautiful apis.

I had to use this work around: use **kwargs parameter, and access the variable via kwargs.get('hub.verify_token').

**Comment by cag** [comment]
Oh interesting, I thought it wouldn't have a workaround at that level. This makes me think that I'm wrong and it would be possible, but then, how should ambiguities that arise from dealing with transforming non identifier field names be handled? Maybe it's for the best.

**Comment by dodysw** [comment]
The parameter, that way, wouldn't be visible when looking through the auto-documentation view. So it's really bypassing hug (by proxy, falcon's) parameter-related features (type validation, routing, documenting, etc) though I'm not familiar with either code base.

To avoid ambiguities, possibly allowing defining parameters through a standard python dict in the decorator. Please no more magical transformation :)

**Comment by cag** [comment]
Hmm, that's not a bad idea. Maybe like some sort of mapping like

```python
@hug.get(param_name_map={'exotic.name': 'plain_name'})
def something(plain_name):
    return do_thing_with(plain_name)
```

And then error or 400 or something when there's still ambiguities.

**Comment by dodysw** [comment]
I like it. Short and succint and solves the problem.

**Comment by timothycrosley** [comment]
Sorry for the delay updating this issue: can confirm support for this has been added to Hug using the `map_params` parameter, as shown here: https://github.com/hugapi/hug/blob/05075500434c4f96c6aa664b925606e4f9952aa6/tests/test_decorators.py#L1916

Thanks!

~Timothy
