### ISSUE TITLE
Local micro-service doesn't accept an Image as return

### ISSUE THREAD

**Issue by imaluengo** [hugapi/hug#447]
According to the documentation, this would be a perfectly valid service:

    import hug
    from PIL import Image

    @hug.get('/hello', output=hug.output_format.png_image)
    @hug.local()
    def hello():
        return Image.new('RGB', (100, 50))

that would return an image. It works perfectly fine if accessed through both Python (local scope) or from a web browser (or other rest client using the standard 8000 port).

However, when running it as a microserver, it works fine if using an `HTTP` microserver:

    ms = hug.use.HTTP('http://localhost:8000/')
    print(ms.get('hello').data)

But it does crash while using a `Local` microserver:

    ms = hug.use.Local(__name__)
    print(ms.get('hello').data)

Throws:

    Traceback (most recent call last):
      File "server.py", line 15, in <module>
        print(ms.get('hello').data)
      File "hug/use.py", line 59, in hug.use.Service.get (hug/use.c:2016)
      File "hug/use.py", line 151, in hug.use.Local.request (hug/use.c:5909)
      File "hug/interface.py", line 611, in hug.interface.HTTP.render_content (hug/interface.c:16006)
    AttributeError: 'Request' object has no attribute 'range'

I might be understanding something wrong. Please let me know, but I think that the following *self-contained* script should work just fine?

    import hug
    from PIL import Image

    @hug.get('/hello', output=hug.output_format.png_image)
    @hug.local()
    def hello():
        return Image.new('RGB', (100, 50))

    client = hug.use.Local(__name__)
    print(client.get('hello').data)

It does work perfectly fine if the return is a `string`, `number` or a `dict`, but it crashes with almost anything else.

PS: I did also try to pass to `Local` an imported module instead of `__name__`, it was just for the purpose of making a self-contained erroneous script.

**Comment by timothycrosley** [comment]
Sorry this issue affected you! I can confirm this issue is resolved in the latest version of Hug.

Thanks!

~Timothy
