### ISSUE TITLE
Problem getting a list with a single element.

### ISSUE THREAD

**Issue by killersacul** [hugapi/hug#719]
I have an entrypoint GET which takes a list as one of the parameters. When I send a list with a single element in said list and try and print it in the my code hug(not 100% sure) splits the word into a list of letters 

Here is the request I make
requests.get("http://localhost/test", data={"list": ["test"]})

And here is the output inside of my entrypoint.
['t', 'e', 's', 't']

I am not sure if this is indented or not but it does mean I do have to reformat my list if there is only one element.

**Comment by GhostofGoes** [comment]
Can you share your hug code?

**Comment by a523** [comment]
I have a same prompled
my code:
```pyhton
@hug.get
def get_hosts_cpu(ips: list):
    print("ips:", ips)`  
```
```shell
curl http://{{host}}/get_hosts_cpu/?ips='["10.201.7.210"]'
```
the print:
```shell
ips: ['[', '"', '1', '0', '.', '2', '0', '1', '.', '7', '.', '2', '1', '0', '"', ']']
```

**Comment by DaveTrost** [comment]
I was able to replicate this problem. **Here are some workarounds**

As mentioned by @a523, using a POST method works all the time to post data that is explicitly a list

If using a GET request is required, use comma-separated values in the GET request **and put a trailing comma after each entry to ensure list-formatted data**
- GET localhost:8000/hosts?ips=10.201.7.210,20.201.7.210,
  - Response = {"ips": ["10.201.7.210", "20.201.7.210"]}
- GET localhost:8000/hosts?ips=10.201.7.210,
  - Response = {"ips": ["10.201.7.210"]}

Here is my hug code:
```
@hug.get('/hosts')
def get_hosts(ips: list):
    return {'ips': ips}
```

I also recommend using Marshmallow for schema typing with field validation. Marshmallow provides very explicit ways to specify typing and seems to provide better input checking. Here is the same code with Marshmallow:
```
from marshmallow import fields


@hug.get('/hosts')
  def get_hosts(ips: fields.List(fields.String())):
    return {'ips': ips}
```

In this specific case of passing a single string, Marshmallow rejects the following query parameter formats with the error "Not a valid list.":
- localhost:8000/hosts?ips=10.201.7.210
- localhost:8000/hosts?ips=[10.201.7.210]
- localhost:8000/hosts?ips=["10.201.7.210"]

**Comment by DaveTrost** [comment]
Pull request #844 has been merged. This PR formalizes testing for all the legal formats for entering a list into the query parameters string.
Please see the above conversation for recommended usage details.
