### ISSUE TITLE
"python -m hug" fails (with possible fix)

### ISSUE THREAD

**Issue by josh2112** [hugapi/hug#770]
Hug 2.4.8 with Python 3.6.5 running on Windows.  `hug -f ${file}` works beautifully; `python -m hug -f ${file}` fails with the following message:

```python.exe: No module named hug.__main__; 'hug' is a package and cannot be directly executed```

The reason I need to run it as a module and not via hug.exe is for Visual Studio Code debugging using the following `launch.json` configuration:

```
{
    "name": "Python: Hug",
    "type": "python",
    "request": "launch",
    "module": "hug",
    "args": [
        "-f",
        "${file}"
    ],
}
```

The error reported is obviously quite true, as there is no `__main__.py` in the hug package.  Using `setup.py` for guidance, I have added one:

```
import hug

hug.development_runner.hug.interface.cli()
```

It works... but is it the right thing to do?

**Comment by GhostofGoes** [comment]
Fixed in https://github.com/hugapi/hug/pull/771

**Comment by josh2112** [comment]
Thanks!

**Comment by timothycrosley** [comment]
This has now made it's way to production in the 2.5.0 release,

Thanks everyone!

~Timothy
