### ISSUE TITLE
webpage should update current version 2.3.2 -> 2.4.8

### ISSUE THREAD

**Issue by bernhardreiter** [hugapi/hug#774]
https://www.hug.rest/ has 2.3.2, where there current release is 2.4.8.

(Is there a better way than opening an issue for this?)

**Comment by GhostofGoes** [comment]
Not sure how the docs are being hosted, however my guess is @timothycrosley just needs to regenerate and update them.

**Comment by timothycrosley** [comment]
Updated! Thanks!

~Timothy
