### ISSUE TITLE
empty query params are not ignored on 2.5.0

### ISSUE THREAD

**Issue by rebkwok** [hugapi/hug#785]
When we have a query param that has `hug.types.multiple`, and an empty query parameter is passed, e.g. `?foo=`, it was parsed as `[]` on 2.4.8 but now is `['']`.  

This is due to one of the breaking changes in falcon 2.0.0 - keep_blank_qs_values now defaults to True instead of False
https://falcon.readthedocs.io/en/stable/changes/2.0.0.html#breaking-changes

Does hug deliberately implement the new falcon default?  I can fix this issue by amending in `api. HTTPInterfaceAPI.server()` with the following: 
```
falcon_api = falcon.API(middleware=self.middleware)
falcon_api.req_options.keep_blank_qs_values = False
```
Is there any way to specify this option when instantiating a hug API?

**Comment by timothycrosley** [comment]
Sorry this error impacted you! This should now be fixed in the 2.5.1 hot-fix release that restores the previous behavior. Additionally, this release makes it easier to directly modify the falcon API as needed during startup:

```
@hug.startup()
def modify_api(api):
    api.falcon.req_options.keep_blank_qs_values = False
```

Thanks!

~Timothy

**Comment by rebkwok** [comment]
Wonderful! Thanks so much for the quick reply.

**Comment by rebkwok** [comment]
@timothycrosley Just FYI, there are another couple of changes to falcon defaults that caused problems for me.  I can fix that in my `hug.startup()` (thanks for that 👍), but I imagine it could cause problems for other users too.
`auto_parse_qs_csv` now defaults to False; which means that `?test=foo,bar` now gets interpreted as ["foo,bar"] by default instead of ["foo", "bar"]
`strip_url_path_trailing_slash` now defaults to False, which caused some previously working calls to 404

**Comment by timothycrosley** [comment]
@rebkwok, thanks for the additional information! I've added a ticket here to resolve: https://github.com/hugapi/hug/issues/790
