### ISSUE TITLE
Show example of map_params

### ISSUE THREAD

**Issue by EdvardM** [hugapi/hug#805]
Found `map_params` from source, but as I couldn't find sample from README and 
eg `from` (for dates) is probably pretty common, added a short example.

PR https://github.com/hugapi/hug/pull/806

**Comment by timothycrosley** [comment]
Closing this as your PR has been merged.

Thank you!

~Timothy

**Comment by EdvardM** [comment]
Thank _you_! This looks _really_ promising, looking forward to write all my Python api's with this ^_^
