### ISSUE TITLE
Please tag v2.6.0

### ISSUE THREAD

**Issue by risicle** [hugapi/hug#825]
Presumably 7367eeb9e885b4b980afa12e314d745eeaf2f624. This is really useful for those who e.g. want to grab a copy of a release version verbatim with the tests included.

**Comment by timothycrosley** [comment]
https://github.com/hugapi/hug/releases/tag/2.6.0

Sorry for this oversight! Agree completely on the usefulness! I'll be looking for a way to automate this within the build process, as right now it is the only manual step I perform.
