### ISSUE TITLE
Trouble with Gunicorn and Supervisor

### ISSUE THREAD

**Issue by pythonBerg** [hugapi/hug#826]
I am encouraged by the Hug's speed as a microservice for NLP processed. I have hit a wall trying to deploy.

My supervisor .conf

```
[program:aicre-nlp-server] 
directory=/home/username/compscre/classify/servers/v21
command=/home/username/compscre/classify/servers/v21/venv/bin/gunicorn --timeout 360 --bind localhost:8090 nlpServer:__hug_wsgi
autostart=true
autorestart=true
logLevel=blather
timeout=300
stderr_logfile=/home/username/compscre/logs/aicre_nlpServer.out.log
stdout_logfile=/home/username/compscre/logs/aicre_nlpServer.err.log 
group=www-data 
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8
```
It appears to be loading correctly...it loads all of the underlying models...and then fails with the only errors being...

```
[2019-09-14 15:37:06 -0400] [15580] [INFO] Starting gunicorn 19.9.0
[2019-09-14 15:37:06 -0400] [15580] [INFO] Listening at: http://127.0.0.1:8090 (15580)
[2019-09-14 15:37:06 -0400] [15580] [INFO] Using worker: sync
[2019-09-14 15:37:06 -0400] [15586] [INFO] Booting worker with pid: 15586
Failed to find application object '__hug_wsgi' in 'nlpServer'

```

Documentation says this is loaded automatically. I see little documentation for deployment and believe I am following it precisely. I suspect there is a config file missing but not sure where to start. 

Thanks

**Comment by timothycrosley** [comment]
@pythonBerg,

Did you end up fixing this issue? Was just about to investigate further: from a brief look it looks like maybe it was just the app name: `__hug_wsgi` vs `__hug_wsgi__`. Let me know if there's anything I can do to clarify the documentation.

Thanks!

~Timothy Crosley

**Comment by pythonBerg** [comment]
It was just that. Rereading doc this evening and caught it finally. Thanks
